import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>TODO LIST</h1>
        <div className={styles.addTask}>
          <div>
            <div className={styles.taskInput}>
              <input type={'string'} placeholder={'Input Task'} />
            </div>
            <div className={styles.otherInput}>
              <input type={'date'} placeholder={'Date'} />
              <input type={'time'} placeholder={'Start Time'} />
              <input type={'time'} placeholder={'End Time'} />
            </div>
          </div>
          <div className={styles.addBtn}>
            <button>ADD</button>
          </div>
        </div>

      </main>
    </>
  )
}
