import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import 'bootstrap/dist/css/bootstrap.css'
import AddTask from '../components/addTask'
import TodoList from '../components/todoList'
import { useState, useEffect } from 'react'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [todos, setTodos] = useState([]);
  const [editTodo, setEditTodo] = useState(null)
  
  const addTask=(data)=>{
    const currentTodo = [...todos, data]
    setTodos(currentTodo)
    localStorage.setItem("todoData", JSON.stringify(currentTodo))
  }



  useEffect(() => {
    /**
     * On page load we need to check if todoData exist in the local storage and if it exist we get the value and set it to the todo value
     */
    const objectData =  localStorage.getItem("todoData") ? JSON.parse(localStorage.getItem("todoData")) : [];
    setTodos( objectData)
    console.log(objectData);
}, []);
  return (
    <>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>TODO LIST</h1>
        <AddTask 
        addTask={addTask} 
        setTodos={setTodos}
        editTodo={editTodo} 
        setEditTodo={setEditTodo} 
        />
        <TodoList 
        todos={todos} 
        setTodos={setTodos} 
        setEditTodo={setEditTodo} 
        />
      </main>
    </>
  )
}
